// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/contact.tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/music.tsx";
import * as $8 from "./routes/projects.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Logo.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/contact.tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/music.tsx": $7,
    "./routes/projects.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Logo.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
